### ISSUE TITLE
Can't delete python engine versioins - it's multiplicated with unknow situation

### ISSUE THREAD

**Issue by ManPython** [pyscripter/pyscripter#1165]
This is msg when want delete some position of versions. I not have this many venvs.. 
![pythons_](https://user-images.githubusercontent.com/25403861/154812301-a6db95c1-b319-496e-a84f-ad466fa542db.png)

**Comment by ManPython** [comment]
Also want suggest option to resize this widow to see full path and more easy edit. Now it's not possible.

**Comment by pyscripter** [comment]
Could you please provide detailed instructions to reproduce the problem?

**Comment by ManPython** [comment]
This what I met:
```
[PythonVersions-x64\Custom Versions]
Path0=Python 3.8 (64bit) -venv=E:\Python38-venv
Path1=Python 3.8 (64bit)=E:\Python38
Path2=Python 3.6 (64bit)=E:\Python36
Path3=Python 3.8 (64bit)=E:\Python38
Path4=Python 3.8 (64bit)=E:\Python38
Path5=Python 3.8 (64bit)=E:\Python38
Path6=Python 3.8 (64bit) -virtualenv=E:\Python38-venv
Path7=Python 3.8 (64bit) -virtualenv=E:\Python38-venv
Path8=Python 3.8 (64bit) -virtualenv=E:\Python38-venv
Path9=Python 3.8 (64bit) -virtualenv=E:\Python38-venv
Path10=Python 3.8 (64bit) -virtualenv=E:\Python38-venv
Path11=Python 3.8 (64bit) -virtualenv=E:\Python38-venv
Path12=Python 3.8 (64bit) -virtualenv=E:\Python38-venv
Path13=Python 3.8 (64bit) -virtualenv=E:\Python38-venv
Path14=Python 3.8 (64bit) -virtualenv=E:\Python38-venv
Count=15
```
After this can't delete from GUI

**Comment by pyscripter** [comment]
I see.  Does the issue occurs only when you reach 16 custom versions?

**Comment by ManPython** [comment]
No. When edited manualy in `PyScripter.local` to 4 this same.

**Comment by pyscripter** [comment]
> Also want suggest option to resize this widow to see full path and more easy edit

Done in version control.

**Comment by pyscripter** [comment]
I cannot reproduce the issue with deleting python versions.  I tried with 15 custom versions and it works fine.
Could you please post here a pyscripter.local.ini that produces the error?

**Comment by ManPython** [comment]
This is old file after edit and deleted positions as upper wit lists that was added from unknown source and method.
Last time I using more VSC, and this was on W10, now have W11 and not wrked yet with PyScripter.
[PyScripter.local.txt](https://github.com/pyscripter/pyscripter/files/9919322/PyScripter.local.txt)

**Comment by pyscripter** [comment]
Fixed in version control.  Thanks for reporting.

**Comment by ManPython** [comment]
Still have problem around ;/
You should check the situation on portable version and if in shortcut is --parameters to open special version of python

**Comment by pyscripter** [comment]
If you use --parameters to open special version of python this takes precedence over the last used version.

**Comment by ManPython** [comment]
It sounds like --Python311 --NEWINSTANCE where I have --Python311-venv
There is problem with this when venv coz Python311-venv\Script\python.exe

**Comment by pyscripter** [comment]
If you want to open the last used python version (venv or not) do not use parameters on the command line such as --Python311.

**Comment by ManPython** [comment]
But sometimes want run special venv directly.. then I used this function, but it's more effectively when python is registered type not venv.
Also it be great to add option for cols auto-reszie col size to show ful path, now is always small size for this dialog.

**Comment by ManPython** [comment]
To be clear... I can delete new versions, but problem is that each run giving new instance.

**Comment by pyscripter** [comment]
> t each run giving new instance.

Do not use --NEWINSTANCE

To run a venv directly you can use the --PYTHONxy and --PYTHONDLLPATH flags together
