### ISSUE TITLE
Debug cause of freezing leading to forced restart

### ISSUE THREAD

**Issue by peetm** [pyscripter/pyscripter#1228]
Occasionally, I find that PyScripter will cease responding and lock-up, requiring a forced process termination.

This usually happens when querying objects' states via the REPL, possibly during debugging (but not sure, I will try and log exactly when in future).  The locking-up appears to exhibit all of the classic signs on a threading, come fatal embrace.  After terminating PyScripter, I also have to go and kill a running Python instance which will typically be consuming around 75% of the CPU.

What is the best method for assisting with the diagnosis of such hangs? Can a mechanism (even if it's simple logging) be added to assist in this?

By the way, this most recently happened on a new Windows 11 machine on which Python (3.11.2) and the latest (current) version of PyScripter was installed for teaching purposes.  So, it's not just my Windows 10 machine.

**Comment by pyscripter** [comment]
> This usually happens when querying objects' states via the REPL

This is related to #1212.  Please wait for the new version that resolves this.

**Comment by pyscripter** [comment]
Please check out version 4.3 and provide feedback regarding this issue.

**Comment by peetm** [comment]
You've a typo in your blog - says 4.2

Peet

**Comment by pyscripter** [comment]
> You've a typo in your blog - says 4.2

Fixed. Thanks!

**Comment by Maxim4711** [comment]
I am not sure, where this issue should be adressed, but it still hangs/freezes in my environment after certain imports. For instance, if i install oracledb with "pip install oracledb" and then have a file with content like
`
import os
import platform
# import oracledb

d = None  # default suitable for Linux
if platform.system() == "Darwin" and platform.machine() == "x86_64":   # macOS
  d = os.environ.get("HOME")+("/Downloads/instantclient_19_8")
elif platform.system() == "Windows":
  d = os.environ.get("ORACLE_HOME")
# oracledb.init_oracle_client(lib_dir=d)

def main():
    print(platform.system())
    print(d)

if __name__ == '__main__':
    main()
`
Then i can run it without any issue, but if i uncomment the line with "import oracledb" - it freezes and pyscripter needs to be restarted.

**Comment by Maxim4711** [comment]
The mentioned behaviour occures only with remote engine, if i use internal engine instead - no hangs are observed

**Comment by Maxim4711** [comment]
I've tried to disable completely defender firewall - despite that the issue still persists with remote engine

**Comment by Maxim4711** [comment]
The regression happened somewhere after 4.2.5 - i tested 4.2.5 with Python 3.11.8 and no freezing happened. With 4.3.4 and Python 3.11.8 it hangs equally as with Python 3.12.2

**Comment by pyscripter** [comment]
Thanks.  I will investigate...

**Comment by pyscripter** [comment]
I found the reason for the freezing:
oracle db starts  the following thread [close_pools_gracefully](https://github.com/oracle/python-oracledb/blob/40d2b9789322ec0eefe43ccf6e86a25e98faf71b/src/oracledb/impl/thin/pool.pyx#L898) which waits for the main thread to finish.

What was added to Pyscripter a few versions back is the following:

```python
                    for t in threading.enumerate():
                        if (t != threading.main_thread()) and not t.daemon:
                            try:
                                t.join()
                            except:
                                pass
```

This is executed after running or debugging a script.   As you can see  the main thread waits for the oracledb thread to finish and oracledb waits for the main thread to finish - hence the blockage.

Whilst I think it is bad design the way the oracledb thread waits for the main thread to finish,  I will consider removing the  PyScripter code that waits for non-deamon threads to finish,

**Comment by pyscripter** [comment]
@Maxim4711 Fixed in version control.   The fix will be available with the next release.

In the meantime you can download the [updated executable](https://drive.google.com/file/d/1j2SjPFx6SQmsZUaKSoJBuujvXHxUhvx1/view?usp=sharing) and test it.   Just replace PyScripter.exe with the one in the zip file.

**Comment by Maxim4711** [comment]
Wow, cool, with 5.0 version the freezing behavior is gone! Thanks a lot for your great support

Regards

Maxim
